name: Deploy to AWS S3 Bucket
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{secrets.node_version}}  

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 4. Build the app
      - name: Build the App
        run: npm run build

      # 5. Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # 6. Deploy to S3 bucket
      - name: Deploy to AWS S3 Bucket
        run: aws s3 sync ./ s3://edson-image-original-2024 --delete
